### ISSUE TITLE
Saving a file does not always completely overwrite the old file

### ISSUE THREAD

**Issue by drbild** [xaptum/xtt#117]
The [`xtt_save_to_file`](https://github.com/xaptum/xtt/blob/5ec88511798b743ac996a5efbe8531c90a004332/src/util/file_io.c#L25) function does not use the `O_TRUNC` flag when opening a file. Consequently, if the new contents are shorter than the old contents, the tail of the old contents remains at the end of the file.

**Comment by zanebeckwith** [comment]
Yep, good catch. Sorry about that.
