### ISSUE TITLE
Support ECDSA key-generation/signing in TPM2.0

### ISSUE THREAD

**Issue by zanebeckwith** [xaptum/xtt#120]
One of the main results of an XTT handshake is the creation of a client's identity ("longterm") keypair (such that the server links the public key with the identity assigned to the client). The private key of this pair is very sensitive (until this client runs another XTT handshake, this private key will be used to prove the client's identity during all subsequent ENF sessions).

Currently, this project saves this identity keypair to disk, in plaintext. To improve the security of this valuable private key, we should generate it on a TPM (secure hardware) such that it never leaves the TPM (and, in fact, is defined to be incapable of leaving the TPM; cf. the TPM flags that can be set during the key's creation).

The `xaptum-tpm` project, which this project links to transitively via its `libecdaa-tpm` dependency (when the `USE_TPM` CMake option is on, of course), already supports ECDSA (using only secp256r1 or p256 or whatever you want to call that curve) key-generation and signing (cf. the `test/tss2_sys_sign-secp256-test.c` file for example usage).

A rough outline of this work could be (all the new code should be wrapped in `USE_TPM` `ifdefs`):
- Add `xtt_crypto_create_ecdsap256TPM_key_pair` and `xtt_crypto_sign_ecdsap256TPM` declarations in `include/xtt/crypto_wrapper.h`
- Create a `src/xaptum_tpm_wrapper.c` file
  - Implement  `xtt_crypto_create_ecdsap256TPM_key_pair` and `xtt_crypto_sign_ecdsap256TPM` in this file, calling the `xaptum-tpm` functions
  - The keypair-generation function will need to make sure it copies the public key out of the TPM structure and into the XTT buffer in the correct format (for later use during the handshake)
- Add a `longterm_sign_ecdsap256TPM` function in `src/internal/crypto_utils.c`
  - This simply calls `xtt_crypto_sign_ecdsap256TPM` (just like `sign_lrswTPM` is a simple wrapper of `xtt_daa_sign_lrswTPM`)
- Add a `xtt_initialize_client_handshake_context_TPM` function to `context.[h,c]`
  - This will be almost the exact same as `xtt_initialize_client_handshake_context`, except it will use `xtt_crypto_create_ecdsap256TPM_key_pair` rather than `xtt_crypto_create_ecdsap256_key_pair`.
  - There's certainly a cleaner way to support these two functionalities, but this is the way the TPM-vs-no-TPM is handled for `xtt_initialize_client_group_context_lrswTPM`, so it seems best to just stick to that for now

The above outline is intended to be a minimal effort plan, and as such doesn't help with the existing poorly-conceived API in this project. While we need to re-architect the crypto design, I think this is important-enough functionality that adding support for it before delving into redesign is a good idea.

Questions:
- How to handle key handle?
  - Should this be a Xaptum-wide-constant, defined in `xaptum-tpm` (like the NVRAM indices, etc.)?
  - Or, should it be user-configurable within this project?

@drbild I'd be interested in your thoughts on this

**Comment by drbild** [comment]
I agree with adding support as outlined here, before re-architecting the internal crypto APIs.

> How to handle key handle?
I think a Xaptum-wide-constant defined in `xaptum-tpm` is the most straightforward approach.  That keeps the definitions for all Xaptum-required handles in one place.  Should there ever be a need for a different handle, it would be easy to modify `xtt` to allow overriding that handle.
