### ISSUE TITLE
Werror breaks the build of downstream users

### ISSUE THREAD

**Issue by drbild** [xaptum/xtt#69]
Enabling`Werror` in the default build tends to break downstream projects on compiler upgrades that introduce new warnings.  Until XTT is updated to reflect these new warnings, the downstream projects can't build.

So, we shouldn't enable `Werror` in the default build.

Instead, introduce a new build type with `Werror`. Run this type in CI, to ensure warning-free builds at the time of merges.

**Comment by zanebeckwith** [comment]
We should be able to set compiler options just for this project (or even just specific directories) in CMake, right?

**Comment by drbild** [comment]
You mean if this project is pulled in via `add_subdirectory` to another CMake project? 

What about a non-CMake project that builds this library by just calling `cmake -DCMAKE_BUILD_TYPE=<type> ...`?

In either case, I don't see any easy way to disable `-Werror` while keeping any other compiler options set by the `xtt` CMakeLists.  Maybe I'm missing something?

**Comment by drbild** [comment]
This came up while publishing `xtt-python` for Python 3.7, to work on @glfejer's new Macbook.

That build was failing, and I thought it was due to warnings from the compiler during the `xtt` compile.  Turns out that wasn't the issue anyway.

**Comment by drbild** [comment]
> I'm confused. What are we trying to prevent? If someone is building this project on a platform we haven't tested on, where that version of that compiler has a warning that we haven't dealt with before?

I'm trying to prevent breaking a working third-party build after a compiler update. I'm less concerned with new platforms/compilers. 

Right now all projects that build `xtt` will break if their respective compilers introduce a new warning.

I ran into this with the function pointer stuff two months ago.  OpenSUSE updated to GCC 8 before Debian 9/Ubuntu, so I couldn't build any project that depended on XTT.

> I know this can get combinatorial real fast, but for a small code base involving crypto, and while the number of platforms it has to work on is limited, I would really like to continue to have this die loudly if we run into a new warning.

I get where you're coming from.

It should definitely die loudly on CI builds.  No disagreement there.

I'm less certain on downstream builds.  Breaking the build is so disruptive to downstream work.

**Comment by zanebeckwith** [comment]
I definitely agree that this should be done, and is the better option. I'm only requesting that we postpone it. 

My interest isn't in catching failures in downstream (though the example you gave of the function pointer issue you ran into was a significant find), but instead in making sure that it dies loudly during development. Our CI is currently minimal on the checking it does (building only with old compilers, with no static analysis or sanitizers, with insufficient tests) so the basic checking of compiler warnings is significant and I really want to make sure it doesn't get ignored accidentally and is found early in the development cycle. 

The number of downstream projects using this is small. Also, this code base is small enough to be able to build with no warnings. The type of issues raised by compiler warnings is useful for this project, involving a lot of casting and pointer arithmetic. 

So I'm only voting that this not be removed until we add more static analysis to our CI.

**Comment by drbild** [comment]
Holding this for now is totally fine.  I agree with your reasoning.  (This was a red herring for my actual issue yesterday anyway.)

I'll propose a few steps here for tracking.  We don't need to move on either of them until you're both back and ready to.  You probably have some specific steps in mind already.

- [ ] Add a "Dev" build type ("DevDebug") that is equivalent to `RelWithDebInfo` ("Debug") but also enables "-Werror".
- [ ] Add the "Dev" ("DevDebug") build types to the CI process.  This will ensure that all merges are warning free on the CI compilers.
- [ ] Get `xtt` developers in the habit of using these "Dev" build types locally.
- [ ] Finally, remove "-Werror" from the "Release", "RelWithDebInfo", and "Debug" builds.

At some point, it would also be good to
- [ ] Try to use the most recent GCC and Clang in the CI environment.  That might mean installing them from a backports repo or something --- no idea what the best way to do this is.

**Comment by zanebeckwith** [comment]
Yea, these points at right on. These will be easy to implement (excepting the up-to-date compilers in CI, especially if we want to avoid requiring sudo in the Travis build).

**Comment by zanebeckwith** [comment]
[This issue](https://github.com/xaptum/xaptum-tpm/pull/44#issue-230248242) in xaptum-tpm can be adapted here to solve this
