### ISSUE TITLE
Update version of XTT in CMake and in homebrew 0.9.3

### ISSUE THREAD

**Issue by kathrynfejer** [xaptum/xtt#72]
There are projects that require XTT > 0.9.2, but in order for a user to locally install xtt 0.9.2 or later they would need to change the number in the CMakeLists.txt themselves or install `xtt-dev` using `apt-get install` which is not possible for Mac users.

**Comment by zanebeckwith** [comment]
@kathrynfejer I'm confused by this issue. Was it just that the version in the `CMakeLists.txt` file was out of date? Has this been fixed by the release of `v0.10.0` (and the new packages in homebrew and bintray)?

**Comment by kathrynfejer** [comment]
Yes, this was resolved with the release of v0.10.0.

**Comment by zanebeckwith** [comment]
Thanks! I love issues that fix themselves...
