### ISSUE TITLE
Taking out examples and updating README

### ISSUE THREAD

**Issue by kathrynfejer** [xaptum/xtt#77]
Now that we have a tool, having the `example/` directory is only useful for the client and server example data it provides. We should keep at least some of the data that the tool cannot yet generate or move the example data into the tool itself.

We should also update the README to reflect these changes a show a user how to run a client and server from the tool.

**Comment by zanebeckwith** [comment]
Good call!

The only files we should need to keep, for now, are the DAA-related ones:
- In the client directory:
  - basename.bin
  - daa_cred.bin
  - daa_gpk.bin
  - daa_secretkey.bin
  - gid.bin
  - server_id.bin (though, this may be temporary, see issue #TODO)
- In the server directory:
  - basename.bin
  - daa_gpk.bin

Once we get a similar tool for the ecdaa project, these files can then be generated by that tool. However, I think we still want to keep these example files even then, just so a user doesn't have to install the ecdaa tool just to run examples (they have to have the ecdaa library, but not necessarily the tool).
